### PR TITLE
KLAX Version 1.3

### PR DESCRIPTION
**Pull request by jamesg31**
Finally got the changes I wanted implemented to my KLAX!

Updates:
- Aircraft types and airlines updated.
- Entry points changed to make the game more playable.
- Replaced the old "SIDS" with 15 accurate SIDS! 5 for KLAX, 6 for KLGB, and 4 for KBUR.

Still got a few more things that it needs but I'm so happy to finally get SoCal to a place I am happy with! Its been a mighty project getting this thing done!

### CODE REVIEW

**Comment by AdamJCavanaugh** [comment]
- [ ] Since you have the KLAX_readme.md, please update that will the new version number and changes?
- [ ] The readme mentions (and airport shows) that "SID's only head directly to their first waypoints. There is no way to model a complex path for a SID, like on the actual SID's." Many of the newer airports have complex routes for both ILS and departures (such as what you have, for departures as well). Could something similar be added in for KLAX?
- [ ] Can you add the chart(s) and/or other tools you've used to the readme so testers can compare?
- [ ] I see https://laartcc.org/airport/view/KLAX has several STARs listed. Would it be possible to add those in?

If you'd rather merge what's already here and add the others as later versions, that's also fine, since it plays/works fine as-is, as well.

**Comment by jamesg31** [comment]
Shoot, forgot to update the readme. The main issue I was looking at with STARS is that there is just no way I could find to properly implement them. Aircraft arrive at the SOCAL tracon already 80% done with their STAR. I have no idea how it works at most airports, but the KLAX STARS start at 30,000 feet and in Norcal / different states. None of this would be practical to implement. In terms of ILS approaches, they are all just straight out from the runways, nothing fancy to get on them so that wouldnt really work anyway. Most of the traffic is vectored off their STAR and onto the visual or ILS.

**Comment by jamesg31** [comment]
Just updated the readme. As I said I just dont think it is possible to implement any of the STARS in a realistic manner. I do have SIDS implemented now so im not sure why your aircraft are only heading to the first waypoint. That was the main addition for this version.

Anyway this should be ready to merge now. Unless you have any ideas for STARS I dont think there is anything else to change right now.

**Comment by thijsschepman** [comment]
Regarding the STAR's, my experience is that it is like that in most places around the world. Also that STAR's are a responsibility of the Area Control Centers and not Approach Radar/TRACON environments (what Endless ATC is simulating). As such adding STAR's makes no sence. What could (and it meant to be) added are approach transitions. These are what lead from the STAR clearance limit onto the actual approach. An example of these are found at EHEH (the airport I moddeled), here the star REDFA3E would take to the the clearance limit EHN via IPTAS, you are transfered from the military ACC after merging point LIKDO to the arrival (TRACON) controller. Which will then either clear you for a transition (e.g. IPTAS1F for RWY21) or give you vectors to final. This last part is what is done by the TRACON controller and it therefore makes sense to simulate the IPTAS1F transition into the airport. It makes no sense to simulate the REDFA3E arrival as that is not the TRACON's responsibility.

**Comment by jamesg31** [comment]
Ahh I see. LAX and most of the west coast / US don't have those I believe. They are pretty european. A few of the eastern STARS lead directly onto the ILS as that is the direction they are coming in from but all of the other STARS are just vectored on.

**Comment by thijsschepman** [comment]
For KLAX specifically, based on a quick look at the charts. Say you are in a westerly configuration (landing 24R and 25L), the ANJLL4 STAR would get you to clearance limit CRCUS. Then if you look at the ILS24R plate, there is a transition from CRCUS, though that is pretty much a straight in. That last part from CRCUS could be simulated as a transition in Endless ATC.

**Comment by jamesg31** [comment]
Yeah thats what I meant by the eastern STARS dumping you on the ILS. CIRCUS is just straight out of the 24R ILS and so it really just makes no sense to include things like that. What would be the difference to click the Circus APP button or just the ILS button? It wouldnt make the controllers life any easier since we dont have aircraft coming in on the ANJLL4 STAR.

**Comment by thijsschepman** [comment]
I do see that KLAX uses some RNAV approaches with a kind off transition. But as the game uses ILS approaches and IRL you said they mostly do vectors to a visual or ILS, I think adding no transitions is the way to go here.

**Comment by jamesg31** [comment]
Yeah I totally agree. @AdamJCavanaugh if your good with this can you merge and close?

**Pull request merged**
