### PR TITLE
VHHH v1.0.1: Init Hong Kong

### PR DESCRIPTION
**Pull request by ycohui**
Init of VHHH

### CODE REVIEW

**Comment by AdamJCavanaugh** [comment]
In the README, you state that this is intended for Android, but I only play/review on PC. I've not noticed any issues from other custom airports when playing on different versions, so I'll review from Steam/PC, but this _may_ be inaccurate, I guess? If so, we'll need to consider placing mobile-only versions separate from airports that support all platforms...

- [ ] The airspace boundary doesn't seem to match what I would expect... there's almost no room to the north and so much to the south I can't even scroll to include it all. Is this intended for leaving room for the future airports? It feels very unfinished as-is. I would recommend either waiting to merge until the other airports are added (to fill out the empty space) or to shrink the airspace down (from the south) for now.
- [ ] The current boundary also means aircraft suddenly "appear" inside the boundary, rather than at the edges of the map, which is preferred.
- [ ] In my testing, I played with 25R active and 25L inactive. I was still able to use approach to vector planes to 25L before the runway/ILS was active, and even land them!. I'd guess this is a game bug, but it should be resolved by just having both runways active from the start, rather than based on score?

**Comment by ycohui** [comment]
1. I think that the version difference between Android and PC should only the monitor size. 
2. Just double checking the northern boundary, maybe it’s missing one point and it kinda close.
3. South are just blank airspace, maybe I will make a hotfix to close it down to APP/DEP/DEH sector only.
4. For traffic sudden appearing in the boundary, I really had no idea about it. But it shall be fixed after reducing the size of sector.
5.  About runway bug, for me v4.2.10 dont had the problem.... May you can try to test it for more time to see its that the one time bug or a real bug.
5a. Just for you to know about the intension of this config. Just want 25L to be active for both but 25R preset for later to open just because of one runway Is incapable to handle such more traffic.

**Comment by ZsBT** [comment]
I've just played it on Android. I think airspace should be expanded a bit more to North.
Also, the two approach endpoints on ILS are close to the each other at the same level, so separation minima breach happens too often. I'd recommend to shift the two points by a few miles or by altitude.

**Comment by ycohui** [comment]
Update on 5.
I've tried out the bug, Even if only South runway is making departure in the scenario, the ILS APCH will be turn on weirdly.
But this don't applied on North Runway....

**Comment by ycohui** [comment]
> ~~I've just played it on Android. I think airspace should be expanded a bit more to North.~~
Fixing

> Also, the two approach endpoints on ILS are close to the each other at the same level, so separation minima incidents happens too often. I'd recommend to shift the two points by a few miles or by altitude.

This airport isn't designed for simultaneous landing, although it's match the minimum separation of two runway. 
Just the values are referencing too. For most non-active runway landing like 25L/07R are usually vectors for final.
So.... This is a still a great idea. Maybe can try it out later but not current version

**Pull request merged**
