### PR TITLE
Add Dalian Zhouzishui International Airport (ZBBB/ZYSH/ZYTL)

### LINKED ISSUE #86: CHN/ZY/ZYTL
the file is done, uploading.

### PR DESCRIPTION
**Pull request by LeoChen98**
Airport file for ZYTL, Dalian Zhouzishui International Airport. close #86 

Created by @savoki0216

### CODE REVIEW

**Comment by AdamJCavanaugh** [comment]
@LeoChen98 , I see you're crediting someone else with the airport.

1. Do you have that person's permission to reproduce it here and add it to this repository?
2. If so, do you wish to work to resolve any issues/questions found? If you don't, is @savoki0216 willing?

**Comment by savoki0216** [comment]
> @LeoChen98 , I see you're crediting someone else with the airport.
> 
> 1. Do you have that person's permission to reproduce it here and add it to this repository?
> 2. If so, do you wish to work to resolve any issues/questions found? If you don't, is @savoki0216 willing?

leo is my friend。Because I don’t know how to use it, please ask him to upload it for me

**Comment by LeoChen98** [comment]
> @LeoChen98 , I see you're crediting someone else with the airport.
> 
> 1. Do you have that person's permission to reproduce it here and add it to this repository?
> 2. If so, do you wish to work to resolve any issues/questions found? If you don't, is @savoki0216 willing?

yep, he asked me to do so, and if there is any problem advise me or savoki is ok

**Comment by AdamJCavanaugh** [comment]
Okay, great, thanks! :)

- [ ] The controllable airspace (and where planes spawn) seems very large for the actual airspace in use. Maybe reduce the size a little, especially to the north and east?
- [ ] The approaches that start right on the edge of the airspace (SANKO, NIXEP, ANRAT) are difficult to use when traffic is heavier (since most aircraft have already flown past them already). Consider either moving that airspace (west and south) further out or the initial beacons a little closer to the airport along the route?
- [ ] Where is ZBBB and ZYSH?
- [ ] It would be good to add some terrain features
- [ ] I'm having a difficult time finding any kind of charts to check accuracy and practices. Would you please consider creating a readme file (named ZYTL_readme.md) with links and explanations? Look at final/JPN/RJBB_readme.md or final/US/CA/KLAX_readme.md for a couple different examples?

**Comment by LeoChen98** [comment]
> Okay, great, thanks! :)
> 
> * [ ]  The controllable airspace (and where planes spawn) seems very large for the actual airspace in use. Maybe reduce the size a little, especially to the north and east?
> * [ ]  The approaches that start right on the edge of the airspace (SANKO, NIXEP, ANRAT) are difficult to use when traffic is heavier (since most aircraft have already flown past them already). Consider either moving that airspace (west and south) further out or the initial beacons a little closer to the airport along the route?
> * [ ]  Where is ZBBB and ZYSH?
> * [ ]  It would be good to add some terrain features
> * [ ]  I'm having a difficult time finding any kind of charts to check accuracy and practices. Would you please consider creating a readme file (named ZYTL_readme.md) with links and explanations? Look at final/JPN/RJBB_readme.md or final/US/CA/KLAX_readme.md for a couple different examples?

* [ ] Airspace and sectors edits need savoki to solve.
* [ ] ZBBB means PRC airspace, and ZYSH means Shenyang flight information region, ZYTL loacted in ZYSH, and ZYSH located in ZBBB.
* [ ] About the terrain, it seems there is no terrain higher than 600 meters or 2000 ft. I think it's no need to add it in?
* [ ] About the readme document, will do, but maybe later. We need some time to do that. And the game file is based on AIP of PRC which published by CAAC, it's the real charts current using. For more information, please check [charts](https://wiki.sinofsx.com/index.php?title=AD_2._%E6%9C%BA%E5%9C%BA_AERODROMES#ZYTL)

**Comment by AdamJCavanaugh** [comment]
For terrain, there's water on the east, isn't there?

**Comment by savoki0216** [comment]
> For terrain, there's water on the east, isn't there?

Search it and you will find that this airport is located on the Liaodong Peninsula. Except for the northern part, the rest is the sea. I don’t think it is necessary to circle its range, but I can set some obstacles according to the aeronautical chart, but it will take some time.
Regarding the issue of airspace, I follow the range given in the "ADS-B and radar fusion operation in the airspace of the Dalian control area" indicated by AD in the aeronautical chart, except for the escrow China and South Korea airway area because that part is not involved Operation of Dalian Airport
You can see the picture below

SharedScreenshot
In the picture, you can also find that in actual operation, there are only four points as the points of the approach procedure, namely CHI, ANRAT, SANKO, NIXEP

**Comment by AdamJCavanaugh** [comment]
Yeah, I understand the realism aspect, I was just thinking more about gameplay... I'll wait a bit and see if anyone else has any comments before doing anything further. :)

**Comment by savoki0216** [comment]
> Yeah, I understand the realism aspect, I was just thinking more about gameplay... I'll wait a bit and see if anyone else has any comments before doing anything further. :)

Add some restricted areas and obstacles (more will be added in the future), add some route displays (currently some routes are not reflected in the AD in the aeronautical chart, and will continue to be modified later), modify the relative position of the runway and The final of RW10. Regarding the scope of the control zone will be adjusted later (approximately)
[ZYTL.txt](https://github.com/AdamJCavanaugh/EndlessATCAirports/files/6196299/ZYTL.txt)

**Comment by LeoChen98** [comment]
Okay, the readme done, and latest version released.

**Pull request merged**
