### PR TITLE
efou airport

### PR DESCRIPTION
**Pull request by obb12**
Heres oulu airport in northern finland

### CODE REVIEW

**Comment by obb12** [comment]
changed

**Comment by AdamJCavanaugh** [comment]
I tried to make a few small updates, but they made a [branch ](https://github.com/AdamJCavanaugh/EndlessATCAirports/compare/efou) in my repo with them, instead. Just some minor markdown tweaks and removing the "example" comments from the actual airport file. Whether or not they're done, I'll merge this after a few days anyways. Looks great to me!

**Comment by obb12** [comment]
ill try and start working on helsinki airport in the coming days

**Comment by ZsBT** [comment]
I've just tried it, seems well playable.

**Review by AdamJCavanaugh — APPROVED** [review]

**Pull request merged**
