### PR TITLE
VHHH TMA 1.0.0

### PR DESCRIPTION
**Pull request by ckwng**
Creating draft PR due to potential file name conflict, not sure how to resolve. Would appreciate any suggestions.

### CODE REVIEW

**Comment by ycohui** [comment]
Nice Integration of VMMC and VHHH
Shall that to be called Extended TMA, or Optimized FIR?
As It's had a larger range of TMA but not the fully FIR...

**Comment by ckwng** [comment]
I'm actually looking for suggestions on file name, as final/AS/HKG/VHHH.txt currently conflicts

**Review by ZsBT — COMMENTED** [review]
I've just played it and it's really enjoyable. 
Arrivals could descend more at MURRY (e.g. FL90) to avoid possible separation incidents. 
But hey, this is a controlled airspace, human intervention is necessary :)
Thanks for your work.

**Comment by ckwng** [comment]
Actually, the altitude restriction at `MURRY` is cross at FL150 for 25s and +FL110-FL130 on the STARs...of course you can always "cancel restrictions" and descend lower, since as you said, that's what the controller is for :)

**Pull request merged**
