### PR TITLE
LSZH 1.2

### PR DESCRIPTION
**Pull request by Beaso14**
Hello, 
Here is an updated LSZH with improved runway configurations, fleet lists and aircraft types. It has SID's that are as realistic as the game currently allows for, (direct routes) but I have contacted Startgrid about this. Struggled to an extreme with ALT restrictions around Zurich so I simplified them massively,(I mean, if someone wants to spend weeks drawing exact polygons mixed with circle shapes that would be awesome haha). I think Startgrid has done a similar thing with the vanilla maps anyway. Otherwise the only things left to do are STARS but most if not all seem to start much much further away than the 30nm distance in the game. Do we make the map bigger (quite easy to do) or simplify the STARS? I don't know. Anyway, take a look and let me know what you think.
Used Jeppensen, Wkiepedia, and Planespotters.net data.
Cheers, Luke

### CODE REVIEW

**Comment by Beaso14** [comment]
BTW you can ignore the 'added files via upload' and 'deleted lszh' commits, I uploaded the file to the wrong place and so deleted it

**Comment by Beaso14** [comment]
There are still some errors - one of the BAW aircraft is broken and the area restrictions are buggy, should be fixed before 1700-1800 GMT.

**Comment by Beaso14** [comment]
@AdamJCavanaugh ?

**Comment by AdamJCavanaugh** [comment]
Based on your previous comment, I was waiting for another update. Was I mistaken? Is there something else I can do for you?

**Comment by Beaso14** [comment]
Sorry for the delay, all done! 👍

**Pull request merged**
