### PR TITLE
Create EFHK

### PR DESCRIPTION
**Pull request by obb12**
[wip] should i add the full arrival routes or keep the short transitions on downwind?

### CODE REVIEW

**Comment by AdamJCavanaugh** [comment]
I had to rename EFHK to EFHK.txt to get it load on PC.

Otherwise, I think everything works well and I'd be fine to merge it.

**Comment by obb12** [comment]
Im happy for it to be merged

**Comment by AdamJCavanaugh** [comment]
Sorry for being unclear. Please rename EFHK to EFHK.txt

**Comment by obb12** [comment]
done

**Pull request merged**
