### PR TITLE
add first version of munich (eddm)

### PR DESCRIPTION
**Pull request by RoAnBu**

### CODE REVIEW

**Comment by AdamJCavanaugh** [comment]
Somehow I missed this for over a month, sorry. Will look soon.

**Comment by AdamJCavanaugh** [comment]
With both approaches at 5000' on the ILS, infringement is possible/common with parallel approaches. Other airports have a 1000' difference between parallel runways to avoid this (as recommended by the in-game help, even). Is the 5000' on both from the charts (for realism) or can 1 be adjusted up or down?

Otherwise, it looks and plays good. If you're willing to move the initial comments (lines 1-20) to a README to match some of the other high-quality airports, that'd be great, as well?

**Review by AdamJCavanaugh — APPROVED** [review]

**Comment by AdamJCavanaugh** [comment]
@RoAnBu, just wanted to see if you had any thoughts on staggering the arrival heights before I merge?

**Comment by RoAnBu** [comment]
> 
> 
> @RoAnBu, just wanted to see if you had any thoughts on staggering the arrival heights before I merge?

I adjusted it. Maybe you can try it again quickly. For now you can merge it when you're happy. I know there is a lot of stuff to improve but I won't have time for that soon. Maybe someone else will pick it up 😆

**Pull request merged**
