### PR TITLE
Create KMIA.txt

### PR DESCRIPTION
**Pull request by FussballxD**
This is KMIA for Endless ATC. It should be in USA-FL but I don't know how to request a new folder. I am unfortunately unable to provide a readme file as I am not familiar with the ATC procedures. The airport is completely based on Charts.

### CODE REVIEW

**Comment by RainbowLegend** [comment]
You can make a new directory just by putting a `/` in the directory (i.e. `/FL/KMIA.txt` under the USA directory). Played the file and it appears accurate and matches up with the IRL charts. I might suggest adding coastlines though -- the airspace looks a little bland right now.

**Comment by FussballxD** [comment]
I am actually not a big fan of coastlines, that is why I removed it. What do you think of adding some waypoints to show on screen so that it'll look a little more alive?

**Comment by RainbowLegend** [comment]
> I am actually not a big fan of coastlines, that is why I removed it. What do you think of adding some waypoints to show on screen so that it'll look a little more alive?

I think extra waypoints is more clutter personally -- I don't know what the MVA in the area looks like (considering FL is a relatively flat state), but there's probably one around the city. Maybe try adding that in?

**Comment by FussballxD** [comment]
I did not find a map i can work with yet, that is why it is not in there unfortunately.

**Comment by RainbowLegend** [comment]
Have you tried looking at the XMLs [here](https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/mva_mia/mva/) yet?

**Comment by AdamJCavanaugh** [comment]
- [ ] As mentioned, please move the file to US/FL/KMIA.txt
- [ ] I'd love a readme... maybe someone on the Discord can help?

I'll wait a bit, since @RainbowLegend had been involved, just to see if anything else is changed. :) But it looks pretty good.

**Pull request merged**
