### PR TITLE
Create EDDK.txt

### PR DESCRIPTION
**Pull request by FussballxD**

### CODE REVIEW

**Comment by AdamJCavanaugh** [comment]
I think it looks good and plays well - pretty similar to some of the vanilla ones, though with more detail/realism.

Points to consider (not needed, if you don't want):
- [ ] Adding approach blocks for the STARs. This is always a balance between realism, playability, and challenge, so just want to make sure it's considered.
- [ ] Adding a EDDK_Readme.md with some basic information and tips (like EDDM or one of the others)?

I'll also leave this open just a little longer in case anyone else wants to review.

**Comment by FussballxD** [comment]
I now added arrival transitions and a short readme will follow
[EDDK.txt](https://github.com/AdamJCavanaugh/EndlessATCAirports/files/6151417/EDDK.txt)

**Comment by FussballxD** [comment]
I just found a small mistake in the file, so here is the corrected version, sorry!
[EDDK.txt](https://github.com/AdamJCavanaugh/EndlessATCAirports/files/6151468/EDDK.txt)

**Comment by AdamJCavanaugh** [comment]
Rather than attaching the files to the PR, can you please update the file in your fork and push so they're included in the listed changes in the PR?

Looking forward to the readme and any other tweaks. :D

**Comment by FussballxD** [comment]
Did I do it correctly now?

**Comment by AdamJCavanaugh** [comment]
Yup! :)

**Comment by FussballxD** [comment]
I accidently uploaded the readme file directly into the final/EU/DEU folder.

**Comment by AdamJCavanaugh** [comment]
I don't see the readme. If it's in the wrong location (what you typed looks correct to me?), fix it, then make sure you commit/push the changes?

**Comment by jamesg31** [comment]
Looks good to me, agree with everything @AdamJCavanaugh said. Just an upgraded version of the vanilla!

**Review by AdamJCavanaugh — APPROVED** [review]

**Pull request merged**
