### PR TITLE
37/ksfo - closes 37

### PR DESCRIPTION
**Pull request by DFEvans**
This PR adds the KSFO airport file I posted on the Steam forums back in July: https://steamcommunity.com/linkfilter/?url=https://pastebin.com/raw/ajHr1wDS

### CODE REVIEW

**Comment by AdamJCavanaugh** [comment]
- [ ] On loading, it gives an error: "Failed to load: h25b e45x"
- [ ] Some of the most popular airports (e.g. RJBB) have custom (and complex) approach vectors for easier management. Is this something that could be added here?
- [ ] Again, other airports (even in USA, like KLAX) often have departures with a plan already in place, rather than simply flying runway heading. Would this be possible to implement? Perhaps it's just my lack of familiarity with the airspace and/or game, but I almost immediately had an issue with departures from 01R and 30OA at almost the same time and altitude that required _immediate_ expedited instructions to avoid an alert.

**Comment by DFEvans** [comment]
> On loading, it gives an error: "Failed to load: h25b e45x"

That relates to the plane types, but I can't for the life of me work out what's upsetting it. The E45X entry is in fact identical to 4+ other entries, other than the name!

Approach/departure vectors are probably worthwhile - they didn't exist when I first created it (or it may have been that STARS existed but didn't work properly).

However, I'm surprised to hear SFO 01L/R and 30OA departures are conflicting. The 01L/R departures should be configured so that they turn right slightly immediately after takeoff to fly directly over OA for exactly that reason, causing them to flying over and behind departures, waiting for radar vectors. Did you wait long enough to see the SFO departures turn? I'm still seeing them do so in the latest Endless ATC version - it's close, but I never managed to catch two planes actually getting into conflict:

image

However, looking closely, I can see that the planes are flying slightly west of the intended TRUKN2 departure track, which would have them pass further behind OA departures:

image

It is a challenging, congested airspace, however - dealing with conflicts makes it fun! I now remember that there's a few diagrams of the routings that I think are worth adding to the readme:

image

**Comment by AdamJCavanaugh** [comment]
1. The list of valid airplanes has been datamined from EATC and posted on the Discord, as well as [here](https://pastebin.com/Dt9eP6mX). It seems that H25B is not valid for EATC (currently) and will need to be removed or replaced.
2. Adding vectors would be much appreciated. If you don't intend to do that on this branch, let me know so I don't keep the PR open for no reason.
3. I probably over-reacted to the near near miss. :) Your departure track is quite close to the diagrams and the challenge makes it well worth playing. If you'd be willing to add some diagrams to the readme in this PR it'd be much appreicated.

Again, if you would rather wait to make any changes, I'll merge this one in as-is, but it would be nice to get the changes in first.

**Comment by DFEvans** [comment]
I got some of the vectors added, with a few more to go - I'll update when I can. It's nice to have the variety of departure tracks, and particularly the ability to set SIDs by runway - one of my annoyances with the original was that international flights should be (mostly) restricted to 28L/R, but there wasn't any way to do this originally.

On Point 1, is that a restrictive list? I thought the point of the plane definition section was that custom planes would be added as desired, in addition to the defaults. For example, the SFO file references BCS1 for A220-100s, which aren't in that data dump. I suspect there's a bug or very subtle issue that I need to ask the developer for help with.

**Comment by AdamJCavanaugh** [comment]
From what I've been told in the (unofficial) Discord, the list is restrictive. If it's not on the list, it won't load.

Thanks for continuing to work. No rush. :)

**Comment by AdamJCavanaugh** [comment]
@DFEvans any update on this?

**Comment by AdamJCavanaugh** [comment]
We're almost at 90 days since the last update. I've asked for any update or assistance on the Discord.

**Pull request closed without merging**
